spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          #          driver-class-name: com.mysql.cj.jdbc.Driver
          #          url: jdbc:mysql://127.0.0.1:3306/voglander?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&serverTimezone =Asia/Shanghai
          #          username: root
          #          password: root
          driver-class-name: org.sqlite.JDBC
          url: jdbc:sqlite:app.db

# hikari 线程池
    hikari:
      max-lifetime: 1800000
      connection-timeout: 5000
      idle-timeout: 3600000
      connection-test-query: /**SELECT 1*/
      maximum-pool-size: 20
      minimum-idle: 10

# redis
  data:
    redis:
      password: luna
      client-name: luna
      database: 0
      timeout: 30
      connect-timeout: 10000


  rabbitmq:
    addresses: 127.0.0.1:5672
    cache:
      connection:
        #       缓存连接模式,默认一个连接,多个channel
        mode: channel
#        多个连接,多个channel
#        mode: connection

# mybatis-plus
mybatis-plus:
  check-config-location: true
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cache-enabled: true # 开启缓存
    use-generated-keys: true # 开启自动生成主键
    default-executor-type: simple # 默认执行器类型
    map-underscore-to-camel-case: true # 开启驼峰命名
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
